<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="po_number"><?php echo Mage::helper('rakuten')->__('Purchase Order Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo Mage::helper('rakuten')->__("Order Number") ?>" class="required-entry input-text" value="<?php echo $this->getInfoData('po_number') ?>"/>
        </div>
    </li>
 <li>
        <div class="input-box">
            <label for="additional_data"><?php echo Mage::helper('rakuten')->__('Payment') ?> <span class="required">*</span></label><br/>
            <input type="text" id="additional_data" name="payment[additional_data]" title="<?php echo Mage::helper('payment')->__("Payment") ?>" class="required-entry input-text" value="<?php echo $this->getInfoData('additional_data') ?>"/>
        </div>
            </li>
</ul>